version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - 0X_DATABASE_DRIVER=postgres
      - 0X_DATABASE_HOST=db
      - 0X_DATABASE_PORT=5432
      - 0X_DATABASE_USER=paste69
      - 0X_DATABASE_PASSWORD=paste69
      - 0X_DATABASE_NAME=paste69
      - 0X_DATABASE_SSLMODE=disable
    volumes:
      - uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=paste69
      - POSTGRES_PASSWORD=paste69
      - POSTGRES_DB=paste69
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paste69"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  uploads:
  postgres_data: 