services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    networks:
      - paste69

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-paste69}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-paste69}
      - POSTGRES_DB=${POSTGRES_DB:-paste69}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-paste69}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "9352:5432"
    networks:
      - paste69

volumes:
  uploads:
  postgres_data:

networks:
  paste69:
