# Database configuration
database:
  # Database driver: "sqlite" or "postgres"
  driver: sqlite
  
  # SQLite configuration
  name: paste69.db  # Database file path for SQLite
  
  # # PostgreSQL configuration (ignored for SQLite)
  # host: localhost
  # port: 5432
  # user: paste69
  # password: paste69
  # sslmode: disable  # Options: disable, require, verify-ca, verify-full

# Storage configuration
storage:
  - name: local
    type: local
    path: ./uploads
    default: true
    
  # - name: s3
  #   type: s3
  #   s3_bucket: paste69-bucket
  #   s3_region: us-east-1
  #   s3_key: your-access-key
  #   s3_secret: your-secret-key
  #   s3_endpoint: https://localhost.localstack.cloud:4566

# Server configuration
server:
  # Server binding address
  address: :3000
  
  # Public-facing URL (used for generating links)
  base_url: http://localhost:3000
  
  # Maximum upload size in bytes (default: 5MB)
  max_upload_size: 5242880  # 5 * 1024 * 1024

  # Preforking
  prefork: false
  
  # Rate limiting configuration
  rate_limit:
    # Global rate limit (across all IPs)
    global:
      enabled: true  # Enable/disable global rate limiting
      rate: 6969.0   # Requests per second
      burst: 250     # Maximum burst size
    
    # Per-IP rate limit
    per_ip:
      enabled: true # Enable/disable per-IP rate limiting
      rate: 2.0    # Requests per second per IP
      burst: 5     # Maximum burst size
    
    # Use Redis for rate limiting if it's available (required for prefork)
    use_redis: false

    # How often to clean up inactive IP limiters
    ip_cleanup_interval: 1h
  
  # Security settings
  security:
    cors_enabled: true
    cors_origins: ["*"]
    cors_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    
    # HTTPS/TLS configuration
    tls_enabled: false
    cert_file: ./certs/cert.pem
    key_file: ./certs/key.pem
  
  # Logging configuration
  logging:
    level: info      # debug, info, warn, error
    format: json     # text or json
    output: stdout   # stdout, stderr, or file path
    
  # Cleanup configuration
  cleanup:
    enabled: true
    interval: 3600   # Cleanup interval in seconds
    max_age: 168h    # Maximum age for temporary pastes (7 days)

# SMTP configuration for sending emails with PostPilot
smtp:
  enabled: true  # Set to true to enable email features
  host: localhost
  port: 1025
  username: 
  password:
  from: noreply@0x45.st
  from_name: Paste69
  starttls: false
  tls_verify: false

# Redis configuration
redis:
  enabled: false
  address: localhost:6379
  password: ""
  db: 0

# Retention configuration
retention:
  no_key:
    min_age: 15.0    # Minimum retention in days
    max_age: 365.0  # Maximum retention in days (1 year)
  with_key:
    min_age: 30.0    # Minimum retention in days
    max_age: 730.0   # Maximum retention in days (2 years)
  points: 50         # Number of points to generate for the curve

# Feature flags (TODO)
features:
  url_shortener: true
  file_preview: true
  syntax_highlighting: true
  api_keys: true
  base_url: http://localhost:3000 