host: 0.0.0.0
port: 8080
site_url: 0.0.0.0:80
use_ssl: false
database_url: sqlite://./db/data.db
templates_dir: src/templates
max_content_length: 268435456 # 256 MiB
max_url_length: 4096
max_ext_length: 9
storage:
  type: local
  path: ./uploads
  max_expiration: 31536000000 # 365 days
  min_expiration: 2592000000  # 30 days
  s3:
    region: null
    bucket: null
    access_key: null
    secret_key: null
  secret_bytes: 16
  ext_override:
    audio/flac: .flac
    image/gif: .gif
    image/jpeg: .jpg
    image/png: .png
    image/svg+xml: .svg
    video/webm: .webm
    video/x-matroska: .mkv
    application/octet-stream: .bin
    text/plain: .txt
    text/x-diff: .diff
  mime_blacklist:
    - application/x-dosexec
    - application/java-archive
    - application/java-vm
  upload_blacklist: null
nsfw:
  detect: false
  theshold: 0.608
vscan:
  socket: null
  quarantine_path: ./quarantine
  interval: 604800 # 7 days
  ignore:
    - Eicar-Test-Signature
    - PUA.Win.Packer.XmMusicFile
url_alphabet: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ