# Database configuration
database:
  driver: sqlite
  host: localhost
  port: 5432
  user: ""
  password: ""
  name: "paste69.db"
  sslmode: disable

# Storage configuration
storage:
  - name: local
    type: local
    path: ./uploads
    default: true

# Server configuration
server:
  # Server binding address
  address: :3000
  
  # Public-facing URL (used for generating links)
  base_url: http://localhost:3000
  
  # Maximum upload size in bytes
  max_upload_size: 5242880      # 5MB default
  default_upload_size: 10485760 # 10MB default
  api_upload_size: 52428800     # 50MB default
  
  # Server identity
  prefork: false
  server_header: "Paste69"
  app_name: "Paste69"
  
  # Directory configuration
  views_directory: "./views"
  public_directory: "./public"
  
  # CORS configuration
  cors_origins: ["*"]
  
  # Rate limiting configuration
  rate_limit:
    # Global rate limit (across all IPs)
    global:
      enabled: true
      rate: 6969.0
      burst: 250
    
    # Per-IP rate limit
    per_ip:
      enabled: true
      rate: 2.0
      burst: 5
    
    # Redis configuration for rate limiting
    use_redis: false
    ip_cleanup_interval: 1h
  
  # Cleanup configuration
  cleanup:
    enabled: true
    interval: 3600
    max_age: "168h"

# SMTP configuration
smtp:
  enabled: false
  host: localhost
  port: 587
  username: ""
  password: ""
  from: ""
  from_name: "Paste69"
  starttls: true
  tls_verify: true

# Redis configuration
redis:
  enabled: false
  address: localhost:6379
  password: ""
  db: 0

# Retention configuration
retention:
  no_key:
    min_age: 7.0     # 7 days minimum
    max_age: 128.0   # 128 days without key
  with_key:
    min_age: 30.0    # 30 days minimum
    max_age: 730.0   # 2 years with key
  points: 50         # Number of points to generate for the curve 