basePath: /
definitions:
  services.APIKeyRequest:
    properties:
      email:
        type: string
      name:
        type: string
    type: object
  services.APIKeyResponse:
    properties:
      key:
        type: string
      message:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: API for 0x45
  license:
    name: MIT
    url: https://github.com/watzon/0x45/blob/main/LICENSE
  title: 0x45 API
  version: "1.0"
paths:
  /api/keys/request:
    post:
      consumes:
      - application/json
      operationId: HandleRequestAPIKey
      parameters:
      - description: Request a new API key
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/services.APIKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/services.APIKeyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/services.APIKeyResponse'
      summary: Request a new API key
      tags:
      - API Key
swagger: "2.0"
