name: Prune containers

on:
  workflow_dispatch:
    inputs:
      container:
        type: string
        required: true
        description: "Container name without organization"
      older-than:
        type: number
        default: 14
        description: "Prune containers older than X days"
      keep-last:
        type: number
        default: 3
        description: "Keep last X containers"

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Prune GHCR containers
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          organization: meikooy
          container: ${{ inputs.container }}
          keep-younger-than: ${{ inputs.older-than }}
          keep-last: ${{ inputs.keep-last }}
          prune-untagged: true